Add Nix Flakes to CI build
acid-info/logos.co pull request #65
Opened 2024-07-24 07:50 UTC by markoburcul

### Description:
The PR introduces usage of Nix Flakes for the purpose of CI build. The goal is to have more control over the versions of tools which are being used within the CI and not depend on what is installed on the CI host.

### Related Issue(s):
[[Link to the related Issue(s), if any.]](https://github.com/status-im/infra-misc/issues/312)

### Changes Included:
- [ ] Bugfix (a change that fixes an issue)
- [ ] New feature (a change that adds new functionality)
- [x] Refactoring (a change that improves code quality and/or architecture)
- [ ] Other (explain below)

### Implementation Details:
By using flake.nix and flake.lock files we are controlling the versions of yarn and nodejs tools which are required by the 'Build' and 'Install' steps in the CI. In this way we won't be dependant on the versions of these tools which are installed on the CI hosts.

### Testing:
I have ran the CI for dev.logos.co which finished successfully and checked the dev.logos.co website afterwards.

### Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

2024-07-24 08:06 UTC, jakubgs requested changes
Your indentation is mixed. You should try using `nix fmt` to format it. But you'll have to set a `formatter` for it to work. I like `nixpkgs-fmt`. You can use `forEachSystem` to set `formatter` in the flake too.

2024-07-24 08:37 UTC, jakubgs commented on Jenkinsfile
> +          nix.develop('yarn install')
Have you tested this? It probably would not work.

2024-07-24 08:45 UTC, siddarthkay commented on Jenkinsfile
> +          nix.develop('yarn install')
I tested this branch locally and this worked for me : `nix develop -c yarn install`

2024-07-24 08:47 UTC, siddarthkay commented on flake.nix
> +                ];
would be cooler to pin down the `nodejs` version here something like 
```suggestion
                packages = with pkgsFor.${system}.buildPackages; [
                    yarn # 1.22.22 
                    nodejs_20_x # v20.15.1
                ];
```

2024-07-25 08:35 UTC, markoburcul commented on Jenkinsfile
> +          nix.develop('yarn install')
I've tested it and it works, here is an example: [Build 149](https://ci.infra.status.im/job/website/job/dev.logos.co/149/console) and [Build 150](https://ci.infra.status.im/job/website/job/dev.logos.co/150/console)

2024-07-25 09:00 UTC, siddarthkay approved these changes
good job!

2024-07-25 09:20 UTC, markoburcul commented on Jenkinsfile
> +          nix.develop('yarn install')
And here is an example with ghp-import from within nix shell: [Build 152](https://ci.infra.status.im/job/website/job/dev.logos.co/152/console)

2024-07-25 12:17 UTC, yakimant approved these changes

2024-07-26 06:43 UTC, jakubgs commented on Jenkinsfile
> +          nix.develop('yarn install')
Oh yeah, i see why I thought that. The `pure` flag actually means:
```groovy
    opts.pure ? "--ignore-environment" : "--impure",
```
https://github.com/status-im/status-jenkins-lib/blob/3e41e5dbe91c22c8f738e47c8bf0c3b477cc395f/vars/nix.groovy#L60

So it is not the same as `--pure` for `nix-shell` where it also implies no network. Cool.

2024-07-26 06:44 UTC, jakubgs approved these changes
Very nice. Will make this build way more robust.

2024-07-26 06:56 UTC, merged